insert into estaciones (nombre, direccion) values ('Gottlieb, Zboncak and Rosenbaum', '57878 Northfield Alley');
insert into estaciones (nombre, direccion) values ('Dickinson, McClure and Kohler', '9 Dixon Pass');
insert into estaciones (nombre, direccion) values ('Schiller Inc', '73 Towne Trail');
insert into estaciones (nombre, direccion) values ('Walter and Sons', '95 4th Hill');
insert into estaciones (nombre, direccion) values ('Schaden-Smith', '931 Anzinger Alley');
insert into estaciones (nombre, direccion) values ('Cronin, Will and Moore', '621 Lakewood Gardens Terrace');
insert into estaciones (nombre, direccion) values ('Lesch-Hoeger', '5302 Heath Point');
insert into estaciones (nombre, direccion) values ('Heidenreich-Kertzmann', '2706 Merchant Way');
insert into estaciones (nombre, direccion) values ('Nikolaus Inc', '22165 Moose Lane');
insert into estaciones (nombre, direccion) values ('Reichel-Balistreri', '7 Pankratz Park');
insert into estaciones (nombre, direccion) values ('Lynch-Nader', '526 Dixon Road');
insert into estaciones (nombre, direccion) values ('Carroll Group', '75 Dexter Circle');
insert into estaciones (nombre, direccion) values ('Heidenreich and Sons', '288 Gale Street');
insert into estaciones (nombre, direccion) values ('Herman Inc', '57052 Sutherland Hill');
insert into estaciones (nombre, direccion) values ('Deckow and Sons', '7557 Nelson Plaza');
insert into estaciones (nombre, direccion) values ('Farrell-Dicki', '06 Kensington Crossing');
insert into estaciones (nombre, direccion) values ('Huels, Howe and Bogisich', '78543 Michigan Court');
insert into estaciones (nombre, direccion) values ('Glover, Krajcik and Bashirian', '96424 Eastlawn Place');
insert into estaciones (nombre, direccion) values ('Mueller-Haley', '7 Scofield Parkway');
insert into estaciones (nombre, direccion) values ('Orn, Mayer and Murphy', '23636 Alpine Pass');
insert into estaciones (nombre, direccion) values ('Lebsack-Schiller', '98110 Cascade Crossing');
insert into estaciones (nombre, direccion) values ('Lang LLC', '34 Anzinger Place');
insert into estaciones (nombre, direccion) values ('Kuhn Group', '1656 Union Parkway');
insert into estaciones (nombre, direccion) values ('Schmeler, Kreiger and Koss', '318 Summit Place');
insert into estaciones (nombre, direccion) values ('Kassulke, Paucek and Olson', '71873 Dawn Pass');
insert into estaciones (nombre, direccion) values ('Kovacek Inc', '8 Sachs Plaza');
insert into estaciones (nombre, direccion) values ('Johnston, Larson and Turner', '80 Scofield Court');
insert into estaciones (nombre, direccion) values ('Sporer, Cassin and Gusikowski', '1905 Garrison Trail');
insert into estaciones (nombre, direccion) values ('Kunde, Doyle and Upton', '69 Golf Point');
insert into estaciones (nombre, direccion) values ('Cartwright Group', '8 Weeping Birch Pass');
insert into estaciones (nombre, direccion) values ('Ledner and Sons', '7942 Southridge Road');
insert into estaciones (nombre, direccion) values ('Erdman LLC', '5041 Hudson Street');
insert into estaciones (nombre, direccion) values ('Hackett-Bernier', '897 Hallows Junction');
insert into estaciones (nombre, direccion) values ('Schiller LLC', '66953 Glendale Plaza');
insert into estaciones (nombre, direccion) values ('Beatty Group', '7 Nova Junction');
insert into estaciones (nombre, direccion) values ('Bashirian-Pouros', '5349 Mallory Crossing');
insert into estaciones (nombre, direccion) values ('Klein, Watsica and Lowe', '916 American Circle');
insert into estaciones (nombre, direccion) values ('Keebler and Sons', '1217 Buell Center');
insert into estaciones (nombre, direccion) values ('Mohr-Effertz', '44 Emmet Road');
insert into estaciones (nombre, direccion) values ('Wisozk-Harvey', '71 John Wall Park');
insert into estaciones (nombre, direccion) values ('Lakin and Sons', '2471 Monterey Street');
insert into estaciones (nombre, direccion) values ('Hane, Olson and Quigley', '93144 Graceland Terrace');
insert into estaciones (nombre, direccion) values ('Harvey-Oberbrunner', '144 Cascade Crossing');
insert into estaciones (nombre, direccion) values ('Monahan-Mraz', '6140 Schmedeman Hill');
insert into estaciones (nombre, direccion) values ('Davis-Hyatt', '07251 Carioca Center');
insert into estaciones (nombre, direccion) values ('Streich and Sons', '03 Shoshone Street');
insert into estaciones (nombre, direccion) values ('Ebert-Bernhard', '6003 Surrey Parkway');
insert into estaciones (nombre, direccion) values ('Schultz-O''Connell', '62649 Kingsford Parkway');
insert into estaciones (nombre, direccion) values ('Morissette LLC', '8039 Service Street');
insert into estaciones (nombre, direccion) values ('Koss, Kulas and Terry', '492 Memorial Pass');
insert into estaciones (nombre, direccion) values ('Kunde LLC', '4152 Tennessee Hill');
insert into estaciones (nombre, direccion) values ('Kreiger and Sons', '32 Glacier Hill Junction');
insert into estaciones (nombre, direccion) values ('Lesch-Ernser', '79506 Carioca Point');
insert into estaciones (nombre, direccion) values ('Yundt and Sons', '74365 Hayes Lane');
insert into estaciones (nombre, direccion) values ('D''Amore-Little', '4 Maple Junction');
insert into estaciones (nombre, direccion) values ('Macejkovic Group', '6534 Onsgard Place');
insert into estaciones (nombre, direccion) values ('Boyer, McKenzie and Volkman', '73 3rd Center');
insert into estaciones (nombre, direccion) values ('Goldner-Pfeffer', '12 Straubel Terrace');
insert into estaciones (nombre, direccion) values ('Ratke Inc', '6808 Main Park');
insert into estaciones (nombre, direccion) values ('Quigley, Balistreri and Walsh', '5150 Pepper Wood Lane');
insert into estaciones (nombre, direccion) values ('Funk-Hudson', '66224 3rd Center');
insert into estaciones (nombre, direccion) values ('Shields, Streich and Carter', '9 Annamark Court');
insert into estaciones (nombre, direccion) values ('Kulas-Schuster', '61208 Continental Street');
insert into estaciones (nombre, direccion) values ('Herman, O''Kon and Rowe', '5273 Crownhardt Alley');
insert into estaciones (nombre, direccion) values ('Legros-Fay', '95 Rigney Crossing');
insert into estaciones (nombre, direccion) values ('Weber Group', '77140 Steensland Way');
insert into estaciones (nombre, direccion) values ('Pouros, Green and Jenkins', '3822 Birchwood Hill');
insert into estaciones (nombre, direccion) values ('Gleason-Romaguera', '26349 Hermina Terrace');
insert into estaciones (nombre, direccion) values ('Bins Group', '6 Nova Road');
insert into estaciones (nombre, direccion) values ('McGlynn LLC', '60472 Almo Hill');
insert into estaciones (nombre, direccion) values ('Bauch-O''Conner', '891 Monument Street');
insert into estaciones (nombre, direccion) values ('Schowalter, Goyette and Doyle', '3510 Weeping Birch Court');
insert into estaciones (nombre, direccion) values ('Satterfield, Rath and Skiles', '65 Dovetail Park');
insert into estaciones (nombre, direccion) values ('McCullough and Sons', '262 Steensland Parkway');
insert into estaciones (nombre, direccion) values ('Stracke-Rohan', '8950 Rigney Plaza');
insert into estaciones (nombre, direccion) values ('Huels-Lockman', '5917 Garrison Park');
insert into estaciones (nombre, direccion) values ('Batz-Schmitt', '60820 Colorado Terrace');
insert into estaciones (nombre, direccion) values ('Schneider and Sons', '30528 Banding Place');
insert into estaciones (nombre, direccion) values ('West, Pfannerstill and Walter', '41 Longview Point');
insert into estaciones (nombre, direccion) values ('Smith-Durgan', '6911 Nova Hill');
insert into estaciones (nombre, direccion) values ('Kovacek-Ullrich', '2207 Shasta Drive');
insert into estaciones (nombre, direccion) values ('Lueilwitz-Kris', '67007 Chive Place');
insert into estaciones (nombre, direccion) values ('Graham, Kirlin and Beer', '43 Mayer Park');
insert into estaciones (nombre, direccion) values ('Huel and Sons', '8368 Hollow Ridge Place');
insert into estaciones (nombre, direccion) values ('Bartoletti, Davis and Zieme', '96 Emmet Circle');
insert into estaciones (nombre, direccion) values ('Bernier-Gutkowski', '2 Judy Circle');
insert into estaciones (nombre, direccion) values ('Marks Inc', '7854 Schmedeman Hill');
insert into estaciones (nombre, direccion) values ('Bernhard, Shanahan and Oberbrunner', '4 La Follette Court');
insert into estaciones (nombre, direccion) values ('White, Kub and Runolfsson', '2 Southridge Parkway');
insert into estaciones (nombre, direccion) values ('Sporer LLC', '3594 Mariners Cove Alley');
insert into estaciones (nombre, direccion) values ('Torphy-Okuneva', '57 Meadow Ridge Center');
insert into estaciones (nombre, direccion) values ('O''Keefe-Lehner', '74985 Emmet Lane');
insert into estaciones (nombre, direccion) values ('Smitham, Rippin and Stark', '4249 Scoville Street');
insert into estaciones (nombre, direccion) values ('Stiedemann, Dooley and Wolff', '23 Emmet Park');
insert into estaciones (nombre, direccion) values ('Ondricka and Sons', '4 Nancy Junction');
insert into estaciones (nombre, direccion) values ('Kessler-Heathcote', '05722 Miller Point');
insert into estaciones (nombre, direccion) values ('Macejkovic-Ledner', '738 Merchant Parkway');
insert into estaciones (nombre, direccion) values ('Kling-Schulist', '33007 Northland Center');
insert into estaciones (nombre, direccion) values ('Schultz-Effertz', '39 West Circle');
insert into estaciones (nombre, direccion) values ('Kuhlman Group', '668 Kedzie Crossing');
