insert into tren (modelo, capacidad) values ('Cobalt', 1);
insert into tren (modelo, capacidad) values ('Alcyone SVX', 2);
insert into tren (modelo, capacidad) values ('Starion', 3);
insert into tren (modelo, capacidad) values ('Sentra', 4);
insert into tren (modelo, capacidad) values ('Yukon Denali', 5);
insert into tren (modelo, capacidad) values ('CX-5', 6);
insert into tren (modelo, capacidad) values ('Aveo', 7);
insert into tren (modelo, capacidad) values ('H3', 8);
insert into tren (modelo, capacidad) values ('Caravan', 9);
insert into tren (modelo, capacidad) values ('Scirocco', 10);
insert into tren (modelo, capacidad) values ('Intrigue', 11);
insert into tren (modelo, capacidad) values ('X-90', 12);
insert into tren (modelo, capacidad) values ('Seville', 13);
insert into tren (modelo, capacidad) values ('QX', 14);
insert into tren (modelo, capacidad) values ('Altima', 15);
insert into tren (modelo, capacidad) values ('Expo', 16);
insert into tren (modelo, capacidad) values ('Lancer', 17);
insert into tren (modelo, capacidad) values ('350Z', 18);
insert into tren (modelo, capacidad) values ('Camaro', 19);
insert into tren (modelo, capacidad) values ('2500 Club Coupe', 20);
insert into tren (modelo, capacidad) values ('Dakota', 21);
insert into tren (modelo, capacidad) values ('Sentra', 22);
insert into tren (modelo, capacidad) values ('C8 Spyder Wide Body', 23);
insert into tren (modelo, capacidad) values ('Ridgeline', 24);
insert into tren (modelo, capacidad) values ('del Sol', 25);
insert into tren (modelo, capacidad) values ('TL', 26);
insert into tren (modelo, capacidad) values ('Express 1500', 27);
insert into tren (modelo, capacidad) values ('A8', 28);
insert into tren (modelo, capacidad) values ('Malibu', 29);
insert into tren (modelo, capacidad) values ('GTI', 30);
insert into tren (modelo, capacidad) values ('Azera', 31);
insert into tren (modelo, capacidad) values ('Veracruz', 32);
insert into tren (modelo, capacidad) values ('Expo LRV', 33);
insert into tren (modelo, capacidad) values ('Diamante', 34);
insert into tren (modelo, capacidad) values ('Golf', 35);
insert into tren (modelo, capacidad) values ('M6', 36);
insert into tren (modelo, capacidad) values ('Regal', 37);
insert into tren (modelo, capacidad) values ('Malibu', 38);
insert into tren (modelo, capacidad) values ('SLR McLaren', 39);
insert into tren (modelo, capacidad) values ('Yukon XL 2500', 40);
insert into tren (modelo, capacidad) values ('Mighty Max', 41);
insert into tren (modelo, capacidad) values ('GTI', 42);
insert into tren (modelo, capacidad) values ('QX', 43);
insert into tren (modelo, capacidad) values ('Sentra', 44);
insert into tren (modelo, capacidad) values ('Hombre', 45);
insert into tren (modelo, capacidad) values ('5 Series', 46);
insert into tren (modelo, capacidad) values ('F250', 47);
insert into tren (modelo, capacidad) values ('Leganza', 48);
insert into tren (modelo, capacidad) values ('TT', 49);
insert into tren (modelo, capacidad) values ('Sedona', 50);
insert into tren (modelo, capacidad) values ('Explorer', 51);
insert into tren (modelo, capacidad) values ('Miata MX-5', 52);
insert into tren (modelo, capacidad) values ('GTI', 53);
insert into tren (modelo, capacidad) values ('Camaro', 54);
insert into tren (modelo, capacidad) values ('Aztek', 55);
insert into tren (modelo, capacidad) values ('E-Class', 56);
insert into tren (modelo, capacidad) values ('Camry', 57);
insert into tren (modelo, capacidad) values ('Passport', 58);
insert into tren (modelo, capacidad) values ('QX', 59);
insert into tren (modelo, capacidad) values ('Bonneville', 60);
insert into tren (modelo, capacidad) values ('Ram Van 2500', 61);
insert into tren (modelo, capacidad) values ('Elise', 62);
insert into tren (modelo, capacidad) values ('Impala', 63);
insert into tren (modelo, capacidad) values ('Sorento', 64);
insert into tren (modelo, capacidad) values ('Uplander', 65);
insert into tren (modelo, capacidad) values ('MX-5', 66);
insert into tren (modelo, capacidad) values ('Previa', 67);
insert into tren (modelo, capacidad) values ('Suburban 1500', 68);
insert into tren (modelo, capacidad) values ('Defender', 69);
insert into tren (modelo, capacidad) values ('Verano', 70);
insert into tren (modelo, capacidad) values ('Camaro', 71);
insert into tren (modelo, capacidad) values ('M5', 72);
insert into tren (modelo, capacidad) values ('Genesis Coupe', 73);
insert into tren (modelo, capacidad) values ('Trooper', 74);
insert into tren (modelo, capacidad) values ('3000GT', 75);
insert into tren (modelo, capacidad) values ('XJ Series', 76);
insert into tren (modelo, capacidad) values ('Ram 3500', 77);
insert into tren (modelo, capacidad) values ('LX', 78);
insert into tren (modelo, capacidad) values ('XR4Ti', 79);
insert into tren (modelo, capacidad) values ('3500', 80);
insert into tren (modelo, capacidad) values ('Outback', 81);
insert into tren (modelo, capacidad) values ('Eclipse', 82);
insert into tren (modelo, capacidad) values ('LS', 83);
insert into tren (modelo, capacidad) values ('Grand Marquis', 84);
insert into tren (modelo, capacidad) values ('Sierra 3500', 85);
insert into tren (modelo, capacidad) values ('FX', 86);
insert into tren (modelo, capacidad) values ('Malibu', 87);
insert into tren (modelo, capacidad) values ('Montero Sport', 88);
insert into tren (modelo, capacidad) values ('Edge', 89);
insert into tren (modelo, capacidad) values ('CX-7', 90);
insert into tren (modelo, capacidad) values ('MPV', 91);
insert into tren (modelo, capacidad) values ('5000CS', 92);
insert into tren (modelo, capacidad) values ('Skylark', 93);
insert into tren (modelo, capacidad) values ('V8 Vantage', 94);
insert into tren (modelo, capacidad) values ('Sierra 2500', 95);
insert into tren (modelo, capacidad) values ('Vega', 96);
insert into tren (modelo, capacidad) values ('CL', 97);
insert into tren (modelo, capacidad) values ('9-2X', 98);
insert into tren (modelo, capacidad) values ('Town Car', 99);
insert into tren (modelo, capacidad) values ('SLK-Class', 100);
