new_sites:
        forbes:
                url: http://forbes.co
                queries:
                       homepage_article_links: ".channel__content a"
        elpais:
                url: https://elpais.com
                queries:
                       homepage_article_links: ".articulo-titulo a"

